"use strict";this.default_VerifiedReviewsGcrBootstrapJs=this.default_VerifiedReviewsGcrBootstrapJs||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k,m=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))},aa=function(a){n.setTimeout(function(){throw a;},0)},n=this||self,ba=/^[\w+/_-]+[=]{0,2}$/,p=null,ca=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ba.test(a)?a:""},q=function(a,b){a=a.split(".");b=b||n;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},r=function(){},
da=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}},t=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
t=ea:t=fa;return t.apply(null,arguments)},ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},u=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.G=function(d,f,g){for(var e=Array(arguments.length-2),h=2;h<arguments.length;h++)e[h-2]=arguments[h];return b.prototype[f].apply(d,e)}},v=function(a){return a};
u(m,Error);m.prototype.name="CustomError";
var ia=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)};
var w;
var y=function(a,b){this.h=a===x&&b||"";this.g=ja},ka=function(a){return a instanceof y&&a.constructor===y&&a.g===ja?a.h:"type_error:Const"},ja={},x={};
var z=function(a,b){this.g=b===la?a:""};z.prototype.toString=function(){return this.g+""};var la={},ma=function(a){if(void 0===w){var b=null;var c=n.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("VerifiedReviewsGcrBootstrapJs#html",{createHTML:v,createScript:v,createScriptURL:v})}catch(d){n.console&&n.console.error(d.message)}w=b}else w=b}a=(b=w)?b.createScriptURL(a):a;return new z(a,la)};
var A=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},C=function(a,b){return a<b?-1:a>b?1:0};
var D;a:{var na=n.navigator;if(na){var oa=na.userAgent;if(oa){D=oa;break a}}D=""}var E=function(a){return-1!=D.indexOf(a)};
var pa=function(a,b){a.src=b instanceof z&&b.constructor===z?b.g:"type_error:TrustedResourceUrl";(b=a.ownerDocument&&a.ownerDocument.defaultView)&&b!=n?b=ca(b.document):(null===p&&(p=ca(n.document)),b=p);b&&a.setAttribute("nonce",b)};
var qa=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},F=function(a){a=String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return qa("0",Math.max(0,2-b))+a},ra=function(){return"position".replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})},sa=function(a){return a.replace(/(^|[\s]+)([a-z])/g,function(b,c,d){return c+d.toUpperCase()})};
var ta=/^(\d{4})(?:(?:-?(\d{2})(?:-?(\d{2}))?)|(?:-?(\d{3}))|(?:-?W(\d{2})(?:-?([1-7]))?))?$/,ua=/^(\d{2})(?::?(\d{2})(?::?(\d{2})(\.\d+)?)?)?$/,va=/Z|(?:([-+])(\d{2})(?::?(\d{2}))?)$/,G=function(a){this.j=this.m=0;this.g=a;this.l=this.i=this.h=0};G.prototype.add=function(a){this.m+=a.m;this.j+=a.j;this.g+=a.g;this.h+=a.h;this.i+=a.i;this.l+=a.l};
var I=function(a,b,c){"number"===typeof a?(this.g=wa(a,b||0,c||1),H(this,c||1)):da(a)?(this.g=wa(a.getFullYear(),a.getMonth(),a.getDate()),H(this,a.getDate())):(this.g=new Date(Date.now()),a=this.g.getDate(),this.g.setHours(0),this.g.setMinutes(0),this.g.setSeconds(0),this.g.setMilliseconds(0),H(this,a))},wa=function(a,b,c){b=new Date(a,b,c);0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b};k=I.prototype;k.getFullYear=function(){return this.g.getFullYear()};k.getMonth=function(){return this.g.getMonth()};
k.getDate=function(){return this.g.getDate()};k.getTime=function(){return this.g.getTime()};k.s=function(){return this.g.getUTCHours()};k.u=function(){return this.g.getUTCMinutes()};k.set=function(a){this.g=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
k.add=function(a){if(a.m||a.j){var b=this.getMonth()+a.j+12*a.m,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.g.setDate(1);this.g.setFullYear(c);this.g.setMonth(b);this.g.setDate(d)}a.g&&(a=new Date((new Date(this.getFullYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.g),this.g.setDate(1),this.g.setFullYear(a.getFullYear()),this.g.setMonth(a.getMonth()),
this.g.setDate(a.getDate()),H(this,a.getDate()))};k.o=function(a){return[this.getFullYear(),F(this.getMonth()+1),F(this.getDate())].join(a?"-":"")};k.v=function(a){return[this.g.getUTCFullYear(),F(this.g.getUTCMonth()+1),F(this.g.getUTCDate())].join(a?"-":"")};k.toString=function(){return this.o()};var H=function(a,b){a.getDate()!=b&&a.g.setUTCHours(a.g.getUTCHours()+(a.getDate()<b?1:-1))};I.prototype.valueOf=function(){return this.g.valueOf()};
var J=function(a,b,c,d,f,g,e){this.g="number"===typeof a?new Date(a,b||0,c||1,d||0,f||0,g||0,e||0):new Date(a&&a.getTime?a.getTime():Date.now())};u(J,I);k=J.prototype;k.s=function(){return this.g.getUTCHours()};k.u=function(){return this.g.getUTCMinutes()};k.add=function(a){I.prototype.add.call(this,a);a.h&&this.g.setUTCHours(this.g.getUTCHours()+a.h);a.i&&this.g.setUTCMinutes(this.g.getUTCMinutes()+a.i);a.l&&this.g.setUTCSeconds(this.g.getUTCSeconds()+a.l)};
k.o=function(a){var b=I.prototype.o.call(this,a);return a?b+"T"+F(this.g.getHours())+":"+F(this.g.getMinutes())+":"+F(this.g.getSeconds()):b+"T"+F(this.g.getHours())+F(this.g.getMinutes())+F(this.g.getSeconds())};k.v=function(a){var b=I.prototype.v.call(this,a);return a?b+"T"+F(this.s())+":"+F(this.u())+":"+F(this.g.getUTCSeconds()):b+"T"+F(this.s())+F(this.u())+F(this.g.getUTCSeconds())};k.toString=function(){return this.o()};
var xa=function(a){var b=new J(2E3);a=A(a);a=a.split(-1==a.indexOf("T")?" ":"T");var c=a[0].match(ta);if(c){var d=Number(c[2]),f=Number(c[3]),g=Number(c[4]);var e=Number(c[5]);var h=Number(c[6])||1;b.g.setFullYear(Number(c[1]));g?(b.g.setDate(1),b.g.setMonth(0),b.add(new G(g-1))):e?(b.g.setMonth(0),b.g.setDate(1),c=b.g.getDay()||7,b.add(new G((4>=c?1-c:8-c)+(Number(h)+7*(Number(e)-1))-1))):(d&&(b.g.setDate(1),b.g.setMonth(d-1)),f&&b.g.setDate(f));e=!0}else e=!1;if(e&&!(e=2>a.length)){e=a[1];a=e.match(va);
if(a)if(e=e.substring(0,e.length-a[0].length),"Z"===a[0])var l=0;else l=60*Number(a[2])+Number(a[3]),l*="-"==a[1]?1:-1;(e=e.match(ua))?(a?b.g.setTime(Date.UTC(b.getFullYear(),b.getMonth(),b.getDate(),Number(e[1]),Number(e[2])||0,Number(e[3])||0,e[4]?1E3*Number(e[4]):0)+6E4*l):(b.g.setHours(Number(e[1])),b.g.setMinutes(Number(e[2])||0),b.g.setSeconds(Number(e[3])||0),b.g.setMilliseconds(e[4]?1E3*Number(e[4]):0)),e=!0):e=!1}return e?b:null};
var ya=E("Opera"),K=E("Trident")||E("MSIE"),za=E("Edge"),Aa=E("Gecko")&&!(-1!=D.toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),Ba=-1!=D.toLowerCase().indexOf("webkit")&&!E("Edge"),L;
a:{var M="",N=function(){var a=D;if(Aa)return/rv:([^\);]+)(\)|;)/.exec(a);if(za)return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ba)return/WebKit\/(\S+)/.exec(a);if(ya)return/(?:Version)[ \/]?(\S+)/.exec(a)}();N&&(M=N?N[1]:"");if(K){var O,Ca=n.document;O=Ca?Ca.documentMode:void 0;if(null!=O&&O>parseFloat(M)){L=String(O);break a}}L=M}var Da=L,Ea={};
var Fa;
if(Fa=K){var Ga;if(Object.prototype.hasOwnProperty.call(Ea,"9"))Ga=Ea["9"];else{for(var P=0,Ha=A(String(Da)).split("."),Ia=A("9").split("."),Ja=Math.max(Ha.length,Ia.length),Q=0;0==P&&Q<Ja;Q++){var Ka=Ha[Q]||"",La=Ia[Q]||"";do{var R=/(\d*)(\D*)(.*)/.exec(Ka)||["","","",""],S=/(\d*)(\D*)(.*)/.exec(La)||["","","",""];if(0==R[0].length&&0==S[0].length)break;P=C(0==R[1].length?0:parseInt(R[1],10),0==S[1].length?0:parseInt(S[1],10))||C(0==R[2].length,0==S[2].length)||C(R[2],S[2]);Ka=R[3];La=S[3]}while(0==P)}Ga=
Ea["9"]=0<=P}Fa=!Ga}var Ma=Fa;
var Na=function(a){var b=document;return"string"===typeof a?b.getElementById(a):a},T=function(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)},Oa={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Pa={IMG:" ",BR:"\n"},Qa=function(a,b,c){if(!(a.nodeName in Oa))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Pa)b.push(Pa[a.nodeName]);else for(a=a.firstChild;a;)Qa(a,b,c),
a=a.nextSibling};
var Ra=function(){this.g={}},Sa=function(a){"string"===typeof a.g.id&&(a.g.id=parseInt(a.g.id,10)||0);return a.g.id||0},Ta=function(a){a=U(a,"badge_position");return"USER_DEFINED"==a||"BOTTOM_LEFT"==a||"BOTTOM_RIGHT"==a?a:"BOTTOM_RIGHT"},Ua=function(a){return U(a,"badge_container")||U(a,"gtsContainer")},Va=function(){var a=V("gts-o-country");return a?/^[A-z]{2}$/.test(a)?a.toUpperCase():a:""},Wa=function(){var a=xa(V("gts-o-est-delivery-date")),b=xa(V("gts-o-est-ship-date"));a||(b?(a=b,a.g.setDate(a.getDate()+
7)):(a=new J,a.g.setTime(Date.now()),a.g.setDate(a.getDate()+10)));return a.v(!0).split("T")[0]},V=function(a){if(a=Na(a)){if(Ma&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Qa(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Ma||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));a=A(a)}else a="";return a},U=function(a,b){var c="";"string"===typeof b&&"undefined"!==typeof a.g[b]&&(c=a.g[b]);"string"===typeof c&&
c&&(c=A(c));return c},Xa=function(a){return"undefined"!==typeof window.gts&&window.gts instanceof Array?(ia(window.gts,function(b){b&&2==b.length&&"string"===typeof b[0]&&(this.g[b[0]]=b[1])},a),!!a.g&&!!Sa(a)):!1};
var Ya={};
var Za=function(a,b){this.h=a;this.g=b},ab=function(a){if(a.g.mcId){var b=T("SCRIPT"),c=ma(ka(new y(x,"https://apis.google.com/js/platform.js")));pa(b,c);b.async=!0;c=[];V("gts-o-id")&&V("gts-o-email")&&Va()&&Wa()&&c.push(t(a.j,a));a.g.showBadge&&("USER_DEFINED"==Ta(a.h)&&Ua(a.h)?$a(a):c.push(t(a.i,a)));b.onload=ia(c,function(d){d()});U(a.h,"locale")&&q("gapi.config").update("lang",U(a.h,"locale"));document.body.appendChild(b)}},$a=function(a){var b=T("g:ratingbadge");b.setAttribute("merchant_id",
a.g.mcId);var c=Ya.position;if(!c){var d=ra();c=d;void 0===b.style[d]&&(d=(Ba?"Webkit":Aa?"Moz":K?"ms":ya?"O":null)+sa(d),void 0!==b.style[d]&&(c=d));Ya.position=c}c&&(b.style[c]="relative");(a=Na(Ua(a.h)))&&a.appendChild(b)};Za.prototype.i=function(){var a=T("div");document.body.appendChild(a);q("gapi.load")("ratingbadge",t(function(){q("gapi.ratingbadge.render")(a,{merchant_id:this.g.mcId,position:Ta(this.h)})},this))};
Za.prototype.j=function(){q("gapi.load")("surveyoptin",t(function(){q("gapi.surveyoptin.render")({merchant_id:this.g.mcId,order_id:V("gts-o-id"),email:V("gts-o-email"),delivery_country:Va(),estimated_delivery_date:Wa(),opt_in_style:this.g.optInStyle})},this))};
var bb=function(a,b){this.i=a;this.j=b;this.h=0;this.g=null};bb.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};var cb=function(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};
var db,eb=function(){var a=n.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!E("Presto")&&(a=function(){var f=T("IFRAME");f.style.display="none";document.documentElement.appendChild(f);var g=f.contentWindow;f=g.document;f.open();f.close();var e="callImmediate"+Math.random(),h="file:"==g.location.protocol?"*":g.location.protocol+"//"+g.location.host;f=t(function(l){if(("*"==h||l.origin==h)&&l.data==e)this.port1.onmessage()},this);g.addEventListener("message",
f,!1);this.port1={};this.port2={postMessage:function(){g.postMessage(e,h)}}});if("undefined"!==typeof a&&!E("Trident")&&!E("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var f=c.A;c.A=null;f()}};return function(f){d.next={A:f};d=d.next;b.port2.postMessage(0)}}return function(f){n.setTimeout(f,0)}};
var fb=function(){this.h=this.g=null};fb.prototype.add=function(a,b){var c=gb.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};var ib=function(){var a=hb,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b},gb=new bb(function(){return new jb},function(a){return a.reset()}),jb=function(){this.next=this.h=this.g=null};jb.prototype.set=function(a,b){this.g=a;this.h=b;this.next=null};jb.prototype.reset=function(){this.next=this.h=this.g=null};
var mb=function(a,b){W||kb();lb||(W(),lb=!0);hb.add(a,b)},W,kb=function(){if(n.Promise&&n.Promise.resolve){var a=n.Promise.resolve(void 0);W=function(){a.then(nb)}}else W=function(){var b=nb;"function"!==typeof n.setImmediate||n.Window&&n.Window.prototype&&!E("Edge")&&n.Window.prototype.setImmediate==n.setImmediate?(db||(db=eb()),db(b)):n.setImmediate(b)}},lb=!1,hb=new fb,nb=function(){for(var a;a=ib();){try{a.g.call(a.h)}catch(b){aa(b)}cb(gb,a)}lb=!1};
var Y=function(a){this.g=0;this.B=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=r)try{var b=this;a.call(void 0,function(c){X(b,2,c)},function(c){X(b,3,c)})}catch(c){X(this,3,c)}},ob=function(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1};ob.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};
var pb=new bb(function(){return new ob},function(a){a.reset()}),qb=function(a,b,c){var d=pb.get();d.j=a;d.h=b;d.i=c;return d},rb=function(a){if(a instanceof Y)return a;var b=new Y(r);X(b,2,a);return b};Y.prototype.then=function(a,b,c){return sb(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};Y.prototype.$goog_Thenable=!0;Y.prototype.cancel=function(a){if(0==this.g){var b=new Z(a);mb(function(){tb(this,b)},this)}};
var tb=function(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var d=0,f=null,g=null,e=c.h;e&&(e.l||(d++,e.g==a&&(f=e),!(f&&1<d)));e=e.next)f||(g=e);f&&(0==c.g&&1==d?tb(c,b):(g?(d=g,d.next==c.j&&(c.j=d),d.next=d.next.next):ub(c),vb(c,f,3,b)))}a.i=null}else X(a,3,b)},xb=function(a,b){a.h||2!=a.g&&3!=a.g||wb(a);a.j?a.j.next=b:a.h=b;a.j=b},sb=function(a,b,c,d){var f=qb(null,null,null);f.g=new Y(function(g,e){f.j=b?function(h){try{var l=b.call(d,h);g(l)}catch(B){e(B)}}:g;f.h=c?function(h){try{var l=c.call(d,
h);void 0===l&&h instanceof Z?e(h):g(l)}catch(B){e(B)}}:e});f.g.i=a;xb(a,f);return f.g};Y.prototype.D=function(a){this.g=0;X(this,2,a)};Y.prototype.F=function(a){this.g=0;X(this,3,a)};
var X=function(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("b"));a.g=1;a:{var d=c,f=a.D,g=a.F;if(d instanceof Y){xb(d,qb(f||r,g||null,a));var e=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(B){h=!1}else h=!1;if(h)d.then(f,g,a),e=!0;else{if(da(d))try{var l=d.then;if("function"===typeof l){yb(d,l,f,g,a);e=!0;break a}}catch(B){g.call(a,B);e=!0;break a}e=!1}}}e||(a.B=c,a.g=b,a.i=null,wb(a),3!=b||c instanceof Z||zb(a,c))}},yb=function(a,b,c,d,f){var g=!1,e=function(l){g||(g=!0,c.call(f,l))},h=function(l){g||
(g=!0,d.call(f,l))};try{b.call(a,e,h)}catch(l){h(l)}},wb=function(a){a.m||(a.m=!0,mb(a.C,a))},ub=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b};Y.prototype.C=function(){for(var a;a=ub(this);)vb(this,a,this.g,this.B);this.m=!1};
var vb=function(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,Ab(b,c,d);else try{b.l?b.j.call(b.i):Ab(b,c,d)}catch(f){Bb.call(null,f)}cb(pb,b)},Ab=function(a,b,c){2==b?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)},zb=function(a,b){a.l=!0;mb(function(){a.l&&Bb.call(null,b)})},Bb=aa,Z=function(a){m.call(this,a)};u(Z,m);Z.prototype.name="cancel";
var Cb,Db=ma(ka(new y(x,"https://apis.google.com/js/api.js"))),Fb=function(){return Eb().then(function(a){return new Y(function(b,c){a.load("gapi.iframes",{callback:ha(b,a),timeout:1E4,ontimeout:function(){c(Error("c`gapi.iframes"))}})})})},Eb=function(){var a=window;return a.gapi?rb(a.gapi):Cb?Cb:Cb=new Y(function(b,c){var d=T("SCRIPT");pa(d,Db);d.onload=function(){b(a.gapi)};d.onerror=function(){c("Failed to load gapi.")};document.getElementsByTagName("head")[0].appendChild(d)})};
(function(){window._DumpException=window._DumpException||function(b){throw b;};var a=new Ra;Xa(a)&&Fb().then(function(){var b=q("gapi.iframes.getContext")(),c=T("div");c.setAttribute("style","position: absolute; width: 1px; height: 1px; left: -10000px; display: none; aria-hidden: true");document.body.appendChild(c);var d=window._gcr_server_address+"/shopping/customerreviews/proxy",f=window.location.href;/(yahoo|shopify.com|luminatestores|shopserve.jp)/.test(f)||(f=window.location.origin);c={url:d,
queryParams:{ts_id:Sa(a),origin:f},allowPost:!1,where:c};b.openChild(c).register("merchantProperty",function(g){ab(new Za(a,g))},q("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",window))},function(){})})();

}catch(e){_._DumpException(e)}
}).call(this,this.default_VerifiedReviewsGcrBootstrapJs);
// Google Inc.
